### PR TITLE
fix: species - the next page button is invisible #785

### LINKED ISSUE #785: Species: The `next page` button is invisible
I don't if this just happens on my browser:

https://admin.treetracker.org/species

Screen Shot 2022-08-16 at 3 41 51 PM

### PR DESCRIPTION
**Pull request by Vlad-Pischaeff**
## Description

_Make all paginator buttons visible_

**Issue(s) addressed**

- Resolves #785

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**Species: The next page button is invisible**

**Species: The next page button is visible**

## Breaking change

**No**

## Other useful information

image

### CODE REVIEW

**Review by nmcharlton — CHANGES_REQUESTED** [review]
Looks like there are some Stakeholder changes from another issue mixed in. Could you remove them?

**Comment by Vlad-Pischaeff** [comment]
Sorry,
How can I remove [fix(stakeholder tool): parent not showing](https://github.com/Greenstand/treetracker-admin-client/pull/788/commits/bdaf88d74a2b1dea60078088ee583d3cd2dc5548) https://github.com/Greenstand/treetracker-admin-client/issues/753 from this PR?

**Comment by Vlad-Pischaeff** [comment]
I'll make new PR

**Comment by nmcharlton** [comment]
Superseded by #807

**Pull request closed without merging**
