### PR TITLE
feat: capture tag removal

### LINKED ISSUE #675: Capture Details: Allow user to remove capture tags
If a user has the `APPROVE_TREE` policy, they should be able to remove capture tags, one by one, from captures via the Capture Details dialog:

1. Capture tag chips (the last ones listed under _Other_) are marked deletable for privileged users (X appears to the right of the label)
2. Clicking the X prompts _Are you sure you wish to remove {name} from this capture?_
3. User clicks _Remove Tag_ to confirm (_Cancel_ option also available).
4. Tag is removed from the capture by calling `DELETE /api/tree_tags/:id`.
5. Tag disappears from the list of chips.

Screenshot 2022-06-02 at 14 20 55

### PR DESCRIPTION
**Pull request by nmcharlton**
## Description

This PR replaces #675. Some additional work is still required.

* Display deletion control on removable capture tags when `appContext.user` has `APPROVE_TREE` policy.
* Separate non-removable tags and capture tags rendering. 

**Issue(s) addressed**

- Resolves #675

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
* Tags are displayed as plain chips

**What is the new behavior?**
* Capture tag chips have a remove icon when appropriate
* Removal requires confirmation

### CODE REVIEW

**Comment by nmcharlton** [comment]
One comment from the original PR still needs to be addressed: https://github.com/Greenstand/treetracker-admin-client/pull/685#pullrequestreview-1048682273

**Comment by maxt0214** [comment]
It looks like all tags are returned in the Capture object as an array of strings from the new api. 

CaptureDetail

Since there are no distinguishment between removable and non-removable tags, we might need to fix the backend api: https://dev-k8s.treetracker.org/query/raw-captures/2495eae6-a091-407d-a69e-63d6e26facaf
or
`${QUERY_API}/raw-captures`

**Comment by nmcharlton** [comment]
@maxt0214 We can treat all `tags` returned by the new API as removable.
We've merged `capture_approval_tag` (`simple_leaf` in your example) into tags and intend to rework the Verify dialog to make it easier for the user to select zero or more common tags.

The selection we currently present as radio buttons is a fairly arbitrary list that made some sense in the early days of the tool, but is outdated now.
Screenshot 2022-12-31 at 16 58 57

**Comment by nmcharlton** [comment]
@maxt0214 We now have the new microservices available, so can migrate away from the legacy API (`/api/admin/api/tree_tags`). The new endpoint is `/treetracker/captures/${captureId}/tags`
I erroneously left in the reference to the legacy APIs when merging the latest `master` branch changes into the PR.

See `createCaptureTags()` and `getCaptureTags()` in `treeTrackerApi.js`.

The code is in [Greenstand/treetracker-api](https://github.com/Greenstand/treetracker-api).
From the code, it looks like you delete a capture tag by `PATCH`ing the resource with `status: "deleted"`
See https://github.com/Greenstand/treetracker-api/blob/main/server/handlers/captureHandler/index.js

You can ignore treetracker-admin-api.

**Comment by maxt0214** [comment]
@nmcharlton 
I have fixed the tag removal. I used api `/captures/:capture_id/tags/:tag_id` with `PATCH` and set status to `deleted`
I used `getCaptureTags()` as you suggested, and the deletion is correctly reflected on `getCaptureTags()` so the deleted tag does not appear in the Capture Detail Panel when the panel is refreshed and reopened.

Screenshot 2023-01-06 160337

There is one issue that I have noticed. The update is not reflected on the `tags` field in the `capture` object. When I try to filter captures by tag, capture that has the tag already removed still appears.

removed

**Comment by nmcharlton** [comment]
Thanks @maxt0214. Could you push your changes to the branch?
It may be best to pass a callback from Verify to trigger a refresh of the capture list when a tag is removed.

**Comment by maxt0214** [comment]
@nmcharlton I don't think I have the write access. Can you give me the write access?

**Comment by nmcharlton** [comment]
@maxt0214 It's probably easiest for you to create a new PR into `master` from your fork. I'll close this one once you've done that.
Just reference this PR and the original issue.

**Comment by nmcharlton** [comment]
Replaced by #1003

**Pull request closed without merging**
