### PR TITLE
feat: include capture location in capture details dialog

### LINKED ISSUE #409: Include capture location in Capture Details dialog
We should display the lat, lon and country in the Capture Details dialog.
For the latter, I'd suggest separating out the `Country()` function in CaptureImage.js into a common component: https://github.com/Greenstand/treetracker-admin-client/blob/11af7be348eb9ba9a8c496fcc0defd3da30367ea/src/components/CaptureMatching/CaptureImage.js#L13

### PR DESCRIPTION
**Pull request by Okwonks**
## Description

_Moving Country to a common component and updating CaptureDetails to use the Country component_

**Issue(s) addressed**

- Resolves #409

**What kind of change(s) does this PR introduce?**

- [X] Enhancement
- [ ] Bug fix
- [X] Refactor

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
- CaptureDetails displays only lat and long

**What is the new behavior?**
- Country name is added to CaptureDetails

### CODE REVIEW

**Comment by nmcharlton** [comment]
@Okwonks This is a great start. Next we need to add Country and Lat/Lon to the Capture Detail dialog, accessible from the _Verify_ and _Captures_ tools:
Screenshot 2022-02-20 at 21 27 45

**Comment by nmcharlton** [comment]
Hey @Okwonks. Are you able to continue your work on this issue?

**Comment by Okwonks** [comment]
> Hey @Okwonks. Are you able to continue your work on this issue?

Hey @nmcharlton, yes I'm still able to work on it.
I will have updates to thee pull request later today.
Sorry for the delay.

**Review by nmcharlton — APPROVED** [review]
@Okwonks Thanks for your efforts on this. For consistency, I've moved the country to the details panel on the right, rather than beneath the image.

**Comment by Okwonks** [comment]
> @Okwonks Thanks for your efforts on this. For consistency, I've moved the country to the details panel on the right, rather than beneath the image.

@nmcharlton You're welcome. Cool, that makes sense 👍 thank you 🙏

**Pull request merged**
