### PR TITLE
feat: add capture tags to Captures table

### LINKED ISSUE #193: Add capture tags to Captures list
We need to be able to see species, tags and other information in the list.

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
## Description

Add Capture Tags to Captures table

**Issue(s) addressed**

- Resolves #193 

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

Don't have the Capture Tags column in Captures table

**What is the new behavior?**

New Capture Tags column in Captures table

## Breaking change

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]
LGTM 🚀

**Comment by nmcharlton** [comment]
@tranquanghuy0801 This looks good. The only thing missing is _Additional tags_, which aren't part of the `trees` LoopBack model, so we have to request them separately using `treeTrackerApi::getCaptureTags()`.
It would be good to try to add these for the listed captures and see what the performance is like.

If that doesn't work well, we may need to modify the API to always return those tags with the capture.

**Comment by nmcharlton** [comment]
> @tranquanghuy0801 This looks good. The only thing missing is _Additional tags_, which aren't part of the `trees` LoopBack model, so we have to request them separately using `treeTrackerApi::getCaptureTags()`. It would be good to try to add these for the listed captures and see what the performance is like.
> 
> If that doesn't work well, we may need to modify the API to always return those tags with the capture.

@tranquanghuy0801 I can take a look at adding in the Additional Tags to the list.

**Comment by nmcharlton** [comment]
image

**Pull request merged**
