### PR TITLE
Feature/html title

### LINKED ISSUE #39: Improve HTML title for Treetracker Admin web pages
The current title, **Greenstand - Tree Tracker**, is not very helpful and breaks the Greenstand communications guidance by splitting Treetracker into two words.

For consistency with the webmap, it should read **Treetracker Admin by Greenstand**

The title should also change dynamically with page changes, e.g. **Verify - Treetracker Admin by Greenstand**

### PR DESCRIPTION
**Pull request by VLuisa**
* Resolves #39 

Default html title is now set to **Treetracker Admin by Greenstand** which is also the title for the 'Home' page.
All other pages are dynamically retitled formatted as: `[Page title] - Treetracker Admin by Greenstand`

I used the Effect hook for the dynamic title updates - open to suggestions if there are better methods!

image
image

### CODE REVIEW

**Comment by VLuisa** [comment]
@nmcharlton I also seem to have fallen prey to a lot of reformatting changes - not sure if there's something I should have done to avoid that?

**Review by nmcharlton — CHANGES_REQUESTED** [review]
Thanks @VLuisa, this looks great!
I agree that `useEffect()` is the best way to change the title.

One suggestion is to pass an empty array as the second parameter (`dependencies`) to `useEffect()` to ensure it is only called once per load.
With no explicit dependencies, the callback is called every time the React render loop fires.

Regarding the reformatting, we have Prettier configured for the project to apply code format standards.
Depending on how your environment is set up, formatting will be applied on either save or commit. It's likely that the code you haven't touched had previously evaded formatting.

**Comment by VLuisa** [comment]
@nmcharlton Thanks for the tip, just made the changes

**Review by nmcharlton — APPROVED** [review]
Perfect, great work @VLuisa!

**Pull request merged**
