### PR TITLE
feat: add disabled save button if userName not unique

### PR DESCRIPTION
**Pull request by zato91**
line 143 add Boolean state userNameValid
line 407 add function HandleUniqueUsername to check duplicate
line 403 called handleUniqueUserName in handleUserNameChange function
line 633 add condition !userNameValid in error 
line 634 add condition userNamevalid in helperText
line 795 add !userNameValid to disabled save button

### CODE REVIEW

**Review by nmcharlton — COMMENTED** [review]
Nice work! Just a couple of minor comments.

**Review by dadiorchen — APPROVED** [review]

**Comment by zato91** [comment]
Awesome, Thank you for the feedback.

**Comment by nmcharlton** [comment]
@zato91 No need to close the PR, just push any additional changes to the branch and they will automatically be included in this PR.

**Comment by zato91** [comment]
line 407- refactored function handleUniqueUsername
line 463 - created handleUserNameError function 
line 638 - called handleUserNameError

**Review by nmcharlton — APPROVED** [review]
Thanks @zato91!

**Pull request merged**
