### PR TITLE
fix: prevent event bubbling for capture table

### LINKED ISSUE #797: Captures: Prevent event bubbling
Сlicking a link "Open in new tab" (http://localhost:3001/captures)

image

causes a click event on a row

image

image

### PR DESCRIPTION
**Pull request by mayankbucha**
## Description

Prevents capture bubbling for open in new tab click.

**Issue(s) addressed**

- Resolves #797 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
Event bubbling causes click to pass through to the table and open details dialog.

**What is the new behavior?**
Event bubbling is stopped.

## Breaking change

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Vlad-Pischaeff** [comment]
"Open in new tab" splits into two lines...
Accidentally You may click between this lines You will call the event of the row, believing that clicking on the "Open in new tab".
To prevent this may be wrap "Open in new tab" into <div>

**Comment by mayankbucha** [comment]
Should I assign min-width to this row?

**Comment by Vlad-Pischaeff** [comment]
I don't think so

сб, 27 авг. 2022 г. в 18:52, Mayank Bucha ***@***.***>:

**Comment by Vlad-Pischaeff** [comment]
In my reply I intended to write "To prevent this may be wrap "Open in new tab" into **div**"

**Review by nmcharlton — APPROVED** [review]

**Pull request merged**
