### PR TITLE
feat: add reset button to tree filter

### PR DESCRIPTION
**Pull request by gwynndp**
This pull is just exploration, open to feedback if I'm going the wrong direction with changes.

### CODE REVIEW

**Comment by nmcharlton** [comment]
Hi @gwynndp, the issue you've mentioned looks unrelated to this change.
Is this addressing an open issue, or just a general improvement?

**Comment by gwynndp** [comment]
I was exploring how the filter worked related to this issue: https://github.com/Greenstand/treetracker-admin-client/issues/26
And added a reset button because it was useful.  I'm not clear what the spec is for the the filter so this is just a draft for the purpose of checking in.

**Review by nmcharlton — CHANGES_REQUESTED** [review]
I'm happy with the reset button implementation, but we should remove the client-side filtering and fix it properly on the server side.

Greenstand/treetracker-admin-api#542 captures the Organization filter bug.
If there are any other problems with what the legacy API returns when a filter is applied, we can raise issues for those against the API project.

**Review by nmcharlton — APPROVED** [review]
Happy days 😎

**Pull request merged**
