### PR TITLE
fix: console errors on login

### PR DESCRIPTION
**Pull request by gwynndp**
Account
- add try/catch to give more informative errors for fetching /permissions and /admin_users
- prevent loading if there's no token
- cleans up 401 errors from calls to /permissions and /admin_users

Context
- logout if session isn't valid, remove 401 condition to logout
- cleans up 401 error if token expires

Login
- fix render error for roles, move the <Typography> tag inside the <Graph> for the role items
- add a new useEffect to redirect once user is added to context

### CODE REVIEW

**Comment by gwynndp** [comment]
This PR may be a fix for https://github.com/Greenstand/treetracker-admin-client/issues/8

**Comment by nmcharlton** [comment]
@gwynndp Are you able to successfully run `npm run build` on your local repo?
It's failing in odd ways in the CI pipeline, and the only change I can see in this PR that may cause problems is `package-lock.json`.

Also, it's a good idea to do the development on a branch in your fork, so that unmerged PRs don't prevent you from doing further development.

**Comment by gwynndp** [comment]
Will do development in feature branches.  I thought I had to merge it back into master to do the pull request.

At some point the package-lock.json got out of sync.  I've been trying to figure my way around that by deleting node-modules and the lock file locally then reinstalling after a rebase but the CI has been failing because modules aren't there anymore in the lock file (?).  I can only assume they were removed or updated to fix vulnerabilities.  So I'll just try to get back in sync.

**Comment by gwynndp** [comment]
I was able to build up to this point.  Now it seems there is a conflict between eslint versions.  Should I delete the one it's complaining about in the package.json? @nmcharlton

**Comment by nmcharlton** [comment]
@gwynndp I've managed get the branch building locally; I hope you don't mind me pushing my changes to your branch.
We'll see if it passes CI.

**Review by nmcharlton — APPROVED** [review]
The changes look good to me

**Comment by nmcharlton** [comment]
I'm going to merge the PR and raise a separate issue to cover the remaining lint errors.

**Pull request merged**
