### PR TITLE
Optimized capture image

### PR DESCRIPTION
**Pull request by gwynndp**
## Description

Update CaptureImage to use OptimizedImage instead of a plain  so that images are loaded faster.

**Issue(s) addressed**

- Resolves #_[367]_https://github.com/Greenstand/treetracker-admin-client/issues/367

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by nmcharlton** [comment]
@gwynndp Do you think you could apply this change to #364?
I made some changes in the area and we're likely to end up with merge issues.

**Comment by nmcharlton** [comment]
There seems to be a problem with statically.io and rotation at the moment. I'm not sure what's causing it, but when our images are served raw, the orientation is correct. When they're served through Statically, they're not rotated.

Raw:
Screenshot 2022-02-07 at 20 19 09
Statically:
Screenshot 2022-02-07 at 20 19 12

**Comment by nmcharlton** [comment]
Statically is returning a png instead of a jpg, so the orientation data is being lost.

**Review by ZavenArra — APPROVED** [review]

**Comment by gwynndp** [comment]
Maybe we should revert this merge until we can figure out the orientation data @ZavenArra 
@nmcharlton Do you think we could load the optimized image and then replace it with the raw image when it loads?

**Comment by nmcharlton** [comment]
> Maybe we should revert this merge until we can figure out the orientation data @ZavenArra 
> 
> @nmcharlton Do you think we could load the optimized image and then replace it with the raw image when it loads?

I agree that we should probably revert. As for loading both, I'm less keen as this will cause a jump in orientation when the raw image loads.

**Comment by gwynndp** [comment]
Status update: 
I can't reproduce this rotation issue but I have looked into a few different libraries that might help us read the EXIF orientation data.  I suspect that if this is an issue we might have to handle it on the server side to make sure the orientation is being stored in S3.  From tests today I'm not getting ANY data from the images stored there but without being able to reproduce the issue in the browser I can't be sure if there is really no data or if the libraries I'm trying aren't working in my tests.

**Pull request merged**
