### PR TITLE
fix: updated unbreaking changes to npm packages

### PR DESCRIPTION
**Pull request by jeremydthomas**
## Description

Updated the npm packages that werent breaking changes. Mui wants to update to v5, looks like a bit of work to do that. Storybrook and Cypress wont update to latest without the MUI update.

**Issue(s) addressed**

- Resolves #issue_number

**What kind of change(s) does this PR introduce?**

- [ x] npm updates

**Please check if the PR fulfils these requirements**

- [x ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

image

List of outdated packages

image

npm audit --production

image

### CODE REVIEW

**Comment by jeremydthomas** [comment]
> Cypress can't be updated to the latest version due to issues with `@cypress/code-coverage` not being compatible with create-react-app in the latest version

Well, that makes more sense, thank you for that explanation.

**Comment by nmcharlton** [comment]
@jeremydthomas Thanks for making some great progress on this. I notice the `lockfileVersion` in package-lock.json has gone from `2` to `1`. Was that intentional? I believe we should be using at least version 2.

I've merged a few other PRs since this was opened; would you be able to resolve the lockfile conflicts against the latest master branch and push the changes?

**Comment by jeremydthomas** [comment]
> @jeremydthomas Thanks for making some great progress on this. I notice the `lockfileVersion` in package-lock.json has gone from `2` to `1`. Was that intentional? I believe we should be using at least version 2.
> 
> I've merged a few other PRs since this was opened; would you be able to resolve the lockfile conflicts against the latest master branch and push the changes?

No, it wasnt intentional at all. Must have happened when I was originally trying to figure things out. I did an npm install and npm said that we should be on 2 and then fixed itself. I just now pulled the new code and did a rebase and pushed it back up. Let me know what you think now @nmcharlton . Also from what I can tell, to use npm install the flag of --legacy-peer-deps will have to be used until we fix cypress to use react 18 as @SuspenseFallback pointed out above. I dont know how big of a project that would be as I'm not really familiar with either one to be honest.


```➜  treetracker-admin-client git:(npm-audit-fix) npm install                          
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @cypress/react@6.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"*" from the root project
npm ERR!   peer react@">=16.3.0" from @emotion/core@10.3.1
npm ERR!   node_modules/@emotion/core
npm ERR!     peer @emotion/core@"^10.0.27" from @emotion/styled@10.3.0
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^10.0.17" from @storybook/theming@5.3.22
npm ERR!       node_modules/@storybook/addons/node_modules/@storybook/theming
npm ERR!         @storybook/theming@"5.3.22" from @storybook/api@5.3.22
npm ERR!         node_modules/@storybook/addons/node_modules/@storybook/api
npm ERR!       1 more (@storybook/theming)
npm ERR!     peer @emotion/core@"^10.0.28" from @emotion/styled-base@10.3.0
npm ERR!     node_modules/@emotion/styled-base
npm ERR!       @emotion/styled-base@"^10.3.0" from @emotion/styled@10.3.0
npm ERR!       node_modules/@emotion/styled
npm ERR!         @emotion/styled@"^10.0.17" from @storybook/theming@5.3.22
npm ERR!         node_modules/@storybook/addons/node_modules/@storybook/theming
npm ERR!         1 more (@storybook/theming)
npm ERR!     4 more (@storybook/theming, @storybook/theming, @storybook/ui, emotion-theming)
npm ERR!   29 more (@emotion/styled, @emotion/styled-base, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^=16.x || ^=17.x" from @cypress/react@6.0.0
npm ERR! node_modules/@cypress/react
npm ERR!   dev @cypress/react@"^6.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^=16.x || ^=17.x" from @cypress/react@6.0.0
npm ERR!   node_modules/@cypress/react
npm ERR!     dev @cypress/react@"^6.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by nmcharlton** [comment]
@jeremydthomas I'm getting some errors when I run `npm start`:
```
Failed to compile.

Module not found: Error: Can't resolve 'fs' in '/Users/nmcha/Development/Greenstand/tac.jeremydthomas/node_modules/dotenv/lib'
ERROR in ./node_modules/dotenv/lib/main.js 24:9-22
Module not found: Error: Can't resolve 'fs' in '/Users/nmcha/Development/Greenstand/tac.jeremydthomas/node_modules/dotenv/lib'

ERROR in ./node_modules/dotenv/lib/main.js 26:11-26
Module not found: Error: Can't resolve 'path' in '/Users/nmcha/Development/Greenstand/tac.jeremydthomas/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

ERROR in ./node_modules/generate-password/src/generate.js 1:13-30
Module not found: Error: Can't resolve 'crypto' in '/Users/nmcha/Development/Greenstand/tac.jeremydthomas/node_modules/generate-password/src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

webpack compiled with 3 errors
```

I'm not sure why we have a reference to `dotenv` in the code – this is more of a backend package.
We import it in `/src/components/OptimizedImage.js` but I think it can be removed.

As for the polyfills, we can add aliases in the package.json dependencies for the browserify packages: https://github.com/facebook/create-react-app/issues/11756#issuecomment-1154197930

There's also an error with `babel-eslint` which can be fixed by replacing that with `@babel/eslint-parser` in `.eslintrc.js`.

Lots of these problems seem to be related to a recent change to create-react-app.

**Review by nmcharlton — APPROVED** [review]
Thanks @jeremydthomas! I've made a few extra tweaks to fix the build and test scripts, and have updated the `@storybook` dependencies.

**Pull request merged**
