### PR TITLE
Capture matching tool merge master

### PR DESCRIPTION
**Pull request by AnitaNa**

### CODE REVIEW

**Comment by TANguyen1893** [comment]
I saw there are some files that you probably didn't want to commit:
- src/.DS_Store
- src/components/.DS_Store
- src/components/CaptureMatching/.DS_Store

Could you remove those from the PR?

**Comment by nmcharlton** [comment]
> I saw there are some files that you probably didn't want to commit:
> 
> - src/.DS_Store
> 
> - src/components/.DS_Store
> 
> - src/components/CaptureMatching/.DS_Store
> 
> 
> 
> Could you remove those from the PR?

Let's add `**/.DS_Store` to `.gitignore`

**Comment by AnitaNa** [comment]
.DS_Store is already in .gitignore.

**Comment by nmcharlton** [comment]
> .DS_Store is already in .gitignore. 

If you add the `**/` prefix, the rule will apply to all directories.

**Comment by nmcharlton** [comment]
Here's the original pull request for this feature: https://github.com/Greenstand/treetracker-admin-api/pull/507

**Comment by nmcharlton** [comment]
@AnitaNa I've fixed the lint errors (mostly just unused variables) and tweaked the logic that populates the candidate trees to use the current capture ID.

I've also extracted the API url and a capture matching feature flag out (to enable or disable the tool) as environment variables in `.env.development`. If you need to do more work on the tool, change the value to be:
```
REACT_APP_ENABLE_CAPTURE_MATCHING=true
```
My intention is to merge this PR into `master`, but keep the feature disabled until it's sufficiently mature and the supporting API is ready.

I'll raise a few GitHub issues to cover the outstanding comments from the original PR so that we can share them around if necessary.

**Review by nmcharlton — APPROVED** [review]
The tool will need a bit more work before it goes live, but is in a good state for merging.
It's disabled in the UI by default but can be enabled by setting `REACT_APP_ENABLE_CAPTURE_MATCHING=true` in `.env.development`.

Additional changes will be captured as GitHub issues.

**Pull request merged**
