### PR TITLE
Earnings and Payments drawer fix

### LINKED ISSUE #597: Earnings & Payments: Dismiss side drawer by clicking background
Throughout the Admin Panel, we allow users to dismiss side drawers by clicking outside the drawer.
This should also apply in the Earnings and Payments tools for the filter, date range and details drawers.
Also, the details drawer should use the same show/hide animation as the filter drawers.

Screenshot 2022-03-28 at 16 02 28

### PR DESCRIPTION
**Pull request by iib0011**
## Description

_[Add a description of the changes]_

**Issue(s) addressed**

- Resolves #597

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by dadiorchen** [comment]
@iib0011 thanks!
@nmcharlton I think we should hold on further change on the earings page, because people are doing test on it, I'm worried new feature/change will bring new bugs, so do you think it's okay to hold on new feature PR for a while and wait until we finished this round of release?

**Comment by iib0011** [comment]
@dadiorchen yes, it is better to wait

**Review by nmcharlton — APPROVED** [review]

**Review by nmcharlton — CHANGES_REQUESTED** [review]
The fix also needs to be applied to `PaymentsTable`

**Review by nmcharlton — APPROVED** [review]
Thanks @iib0011!

**Pull request merged**
